[package]
name = "rising-padel-manager"
version = "3.1.0"
description = "Rising Pádel Manager"
authors = ["Rising Games"]
edition = "2021"

[build-dependencies]
tauri-build = { version = "2.0.0", features = [] }

[dependencies]
tauri = { version = "2.0.0", features = [] }
rusqlite = { version = "0.31", features = ["bundled"] }

[profile.release]
panic = "abort"
codegen-units = 1
lto = true
opt-level = "s"
strip = true
